server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:config/log4j2.xml

spring:
  datasource:
    url: jdbc:mysql://120.25.238.219:2556/gxucpc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始状态数量
      initial-size: 5
      #最小连接数
      min-idle: 5
      #最大连接数
      max-active: 20
      #毫秒
      max-wait: 60000
  data:
    mongodb:
      uri: mongodb://root:123456@120.25.238.219:3555/store?authSource=admin
  mail:
    default-encoding: UTF-8
  jackson:
    # 队友null的属性不解析为JSON
    default-property-inclusion: non_null

mybatis:
  mapper-locations: classpath:mapper/*.xml

buffSize: 10240