server:
  port: 80
  tomcat:
    uri-encoding: UTF-8

logging:
  config: classpath:log4j2.xml

spring:
  datasource:
    url: jdbc:mysql://42.192.36.136:3555/gxucpc?useUnicode=true&characterEncoding=utf-8&serverTimezone=Hongkong
    username: root
    password: mysql114514
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始状态数量
      initial-size: 5
      #最小连接数
      min-idle: 5
      #最大连接数
      max-active: 20
      #毫秒
      max-wait: 60000

  data:
    mongodb:
      uri: mongodb://admin:mongodb114514@42.192.36.136:2556/File?authSource=admin

mybatis:
  mapper-locations: classpath:mapper/*.xml

